[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 500

[theme]
primaryColor = "#0284c7"
backgroundColor = "#f8fafc"
secondaryBackgroundColor = "#0f172a"
textColor = "#0f172a"
font = "sans serif"

[browser]
gatherUsageStats = false
